{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "grafana.fullname" . }}
  {{- if .Values.serviceMonitor.namespace }}
  namespace: {{ tpl .Values.serviceMonitor.namespace . }}
  {{- else }}
  namespace: {{ include "grafana.namespace" . }}
  {{- end }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- tpl (toYaml . | nindent 4) $ }}
    {{- end }}
spec:
  endpoints:
  - port: {{ .Values.service.portName }}
    {{- with .Values.serviceMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
    honorLabels: true
    path: {{ .Values.serviceMonitor.path }}
    scheme: {{ .Values.serviceMonitor.scheme }}
    {{- with .Values.serviceMonitor.tlsConfig }}
    tlsConfig:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- /* Only render metricRelabelings if there will be at least one item, to prevent SSA null issue */ -}}
    {{- $hasExtra := or .Values.global.cattle.clusterId .Values.global.cattle.clusterName -}}
    {{- if or .Values.serviceMonitor.metricRelabelings $hasExtra }}
    metricRelabelings:
      {{- with .Values.serviceMonitor.metricRelabelings }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.global.cattle.clusterId }}
      - sourceLabels: [__address__]
        targetLabel: cluster_id
        replacement: {{ .Values.global.cattle.clusterId }}
      {{- end }}
      {{- if .Values.global.cattle.clusterName }}
      - sourceLabels: [__address__]
        targetLabel: cluster_name
        replacement: {{ .Values.global.cattle.clusterName }}
      {{- end }}
    {{- end }}

    {{- with .Values.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.serviceMonitor.basicAuth }}
    basicAuth:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  jobLabel: "{{ .Release.Name }}"
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ include "grafana.namespace" . }}
  {{- with .Values.serviceMonitor.targetLabels }}
  targetLabels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
